version: '3.3'
services:
  db:
    image: mysql:8.0.23
    container_name: mysql-dc-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-test:/var/lib/mysql

volumes:
    mysql-test:
